# Generated by Django 2.0.3 on 2018-04-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markdown', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markdownartical',
            old_name='artical_html',
            new_name='markdown_text',
        ),
    ]
