# Generated by Django 2.0.3 on 2018-05-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markdown', '0003_auto_20180501_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markdownartical',
            options={'verbose_name': '文章(Markdown)', 'verbose_name_plural': '文章(Markdown)'},
        ),
        migrations.AddField(
            model_name='markdownartical',
            name='auther',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='作者'),
        ),
    ]
