# Generated by Django 2.0.3 on 2018-05-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markdown', '0004_auto_20180501_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markdownartical',
            name='link_address',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='转载地址'),
        ),
    ]
