# Generated by Django 2.0.3 on 2018-05-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markdown', '0005_auto_20180502_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markdownartical',
            name='title',
            field=models.CharField(max_length=255, verbose_name='标题'),
        ),
    ]
