# Generated by Django 2.0.3 on 2018-04-25 03:13

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180417_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='markdownArtical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='标题')),
                ('artical_html', users.models.EditorMarkdownField(blank=True, default='', verbose_name='内容')),
            ],
        ),
    ]
