# Generated by Django 2.0.3 on 2018-04-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180430_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverifyrecord',
            old_name='eamil',
            new_name='email',
        ),
    ]
