# Generated by Django 2.0.3 on 2018-04-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180430_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='images/lady_default.jpg', upload_to='images/%Y/%m', verbose_name='用户头像'),
        ),
    ]
