# Generated by Django 2.0.3 on 2018-05-01 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180501_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markdownartical',
            options={},
        ),
        migrations.RemoveField(
            model_name='markdownartical',
            name='auther',
        ),
        migrations.RemoveField(
            model_name='markdownartical',
            name='link_address',
        ),
        migrations.RemoveField(
            model_name='markdownartical',
            name='original',
        ),
        migrations.RemoveField(
            model_name='markdownartical',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='markdownartical',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='markdownartical',
            name='update_time',
        ),
    ]
