# Generated by Django 2.0.3 on 2018-04-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('use_ckeditor', '0002_web_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='web_link',
            options={'verbose_name': '常用站点', 'verbose_name_plural': '常用站点'},
        ),
        migrations.AlterField(
            model_name='web_link',
            name='address',
            field=models.URLField(max_length=256, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='web_link',
            name='name',
            field=models.CharField(max_length=256, verbose_name='网站名称'),
        ),
    ]
