# Generated by Django 2.0.3 on 2018-04-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('use_ckeditor', '0008_auto_20180410_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='link_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='转载地址'),
        ),
        migrations.AddField(
            model_name='article',
            name='original',
            field=models.BooleanField(choices=[('True', '是'), ('False', '否')], default='True', max_length=3, verbose_name='是否原创'),
        ),
    ]
