# Generated by Django 2.0.3 on 2018-04-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('use_ckeditor', '0012_auto_20180410_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='original',
            field=models.BooleanField(default=False),
        ),
    ]
