# Generated by Django 2.0.3 on 2018-05-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('use_ckeditor', '0016_article_auther'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章（富文本）', 'verbose_name_plural': '文章（富文本）'},
        ),
    ]
