# Generated by Django 2.0.3 on 2018-05-04 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('use_ckeditor', '0019_auto_20180504_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web_link',
            name='tag',
        ),
    ]
