# Generated by Django 2.0.3 on 2018-05-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('use_ckeditor', '0020_remove_web_link_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_link',
            name='tag',
            field=models.ManyToManyField(blank=True, to='use_ckeditor.Web_type', verbose_name='网站分类'),
        ),
    ]
