# Generated by Django 2.0.3 on 2018-05-04 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('use_ckeditor', '0021_web_link_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web_link',
            name='tag',
        ),
        migrations.AddField(
            model_name='web_link',
            name='web_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='use_ckeditor.Web_type', verbose_name='网站分类'),
        ),
        migrations.AlterField(
            model_name='web_type',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='网站分类'),
        ),
    ]
